name: Hello World
on:
  push:
    branches:
      - main

jobs: 
  system_info:
    runs-on: ubuntu-latest
    
    steps:
    - name: Say Hello
      run: echo "hello, World"
      
    - name: no name
      run: cat /etc/os-release
      
    - name: date and time:
     run: date
   
